baseURL = "http://example.org/"
languageCode = "en-us"
title = "Päkstech.dev"
theme = "bloggeri"
paginate = 4

[params]
    description = "My site description"
    author = "Morgan Kenyon"
    authorImage = "/images/masteringHugo.png"

[[menu.main]]
    name = "About"
    url = "/about"
[[menu.main]]
    name = "Blog"
    url = "/blog"
[[menu.main]]
    name = "Contact"
    url = "/contact"
[[menu.main]]
    name = "Categories"
    url = "/categories"    
[[menu.social]]
    name = "GitHub"
    url = "https://github.com/pakstech"
    pre = "<i class='fab fa-github'></i>"
[[menu.social]]
    name = "YouTube"
    url = "https://www.youtube.com/channel/UCg_e3UBPs-BxPo_jVg1gGOQ"
    pre = "<i class='fab fa-youtube'></i>"
[[menu.social]]
    name = "Twitter"
    url = "https://twitter.com/pakstech"
    pre = "<i class='fab fa-twitter'></i>"

[[menu.footer]]
  name = "About"
  url = "/about"
[[menu.footer]]
  name = "Privacy"
  url = "/privacy"
